name: DiscordToMinecraft
version: 1.0.0
main: MCPlayingTV\Discord2Minecraft
api: 3.0.0

author: MCPlayingTV
website: https://rconcraft.ml/docs/d2m
commands:
  rcsay:
    description: Bot Say Command
    usage: "/rcsay"
    permission: rconcraft.command.say
    permission-message: "You don't have permission to use this command!"
  d2m:
    description: DiscordToMinecraft
    usage: "/d2m"
    permission: "rconcraft.command.d2m
    permission-message: "You don't have permission to use this command!"
