name: DiscordToMC
version: 1.0.0
main: MCPlayingTV\DiscordToMC
api: 3.0.0

author: MCPlayingTV
website: https://rconcraft.ml/docs/d2m
commands:
  rcsay:
    description: Bot Say Command
    permission: dtm.command.say
  discordtominecraft:
    description: Setup DiscordToMinecraft
    permission: dtm.command.dtm
